### PR TITLE
Allow Indexing with Java 8

### PR DESCRIPTION
**Pull request by gselzer**
Should enable seamless Op indexing in ImgLib2 projects.

@hinerm - do you see any pure-POM way to enable this? I had to make a lot of unfortunate changes to the code to make it Java-8 compliant, however I feel like that shouldn't be necessary, if we instead set `maven.compiler.source`/`maven.compiler.target`. Do you know what I did wrong?

### CODE REVIEW

**Comment by hinerm** [comment]
@gselzer I don't think there's a way to use newer Java language features in older Java runtimes. What you did seems appropriate. I am curious why it was necessary though?

**Comment by gselzer** [comment]
> I am curious why it was necessary though?

My goal is to enable Op indexing within projects that may not be ready to transition to Java 11 (see imglib/imglib2-mesh#10, imglib/imglib2-algorithm#94). If you attempt to use `org.scijava:scijava-ops-indexer:1.0.0` compiling with Java 8, you'll receive compilation errors:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error: Could not load processor class file due to 'org/scijava/ops/indexer/OpImplNoteParser has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0'.
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.523 s
[INFO] Finished at: 2024-06-25T08:52:41-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project
 imglib2-mesh: Compilation failure
[ERROR] error: Could not load processor class file due to 'org/scijava/ops/indexer/OpImplNoteParser has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0'.
[ERROR]
[ERROR] -> [Help 1]
```

**Comment by gselzer** [comment]
However many of the changes (specifically deleting the `module-info.java`) I find to be a step backwards

**Review by ctrueden — COMMENTED** [review]
I am torn on this. For the module-info.java specifically, we could maybe keep it but move it to the `META-INF/versions` tree. But the code changes to regress the source compatibility back to 8 from 11+ feels bad, indeed. OTOH, it's not very many changes—maintenance-wise, probably pretty easy to keep working for quite some time still. Since @gselzer already did the work, I guess the main thing is just to test whether `META-INF/versions` works for the `module-info.java`?

**Comment by ctrueden** [comment]
Current plan is to change Java-8-dependent projects to have a Java-11+ build time requirement, but still target Java 8 bytecode via the `--release` flag. Then those projects can depend on the scijava-ops-indexer as is, even though it's built targeting Java 11 bytecode. And we won't have to devolve the code back to Java 8 syntax here. :see_no_evil:

**Pull request closed without merging**
